### PR TITLE
49 linkit file upload

### PR DESCRIPTION
**Pull request by genjohnson**
This PR addresses issues #49 and #93 by:
- allowing File media entities to be chosen through LinkIt which results in a link directly to the file (rather than the File entity)
- adding an entity browser widget to the LinkIt modal so that files can be uploaded within the context of adding a link in the WYSIWYG
- removing the "Upload File(s)" tab from the "Add media" Entity Embed modal in the WYSIWYG (since Entity Embed doesn't currently play nicely with inline elements such as links)
- replacing the view at `admin/content/files` with a view of File media entities
- removing File media entities from the Media view at `admin/content/media`

### CODE REVIEW

**Comment by briand44** [comment]
More testing and more comments to come but I noticed that after using linkit to upload and link to a file, when viewing the file the first time it linked directly to the file but after saving the node it began linking to the file entity.

**Comment by adamdelaney** [comment]
I can confirm that directly linking to the file breaks after re-editing the page. I believe that the attributes are getting stripped when you re-edit the page and then get saved that way.

screen shot 2018-08-13 at 3 24 43 pm

**Comment by adamdelaney** [comment]
I'm not quite sure what this is:
> replacing the view at admin/content/files with a view of File media entities

> removing File media entities from the Media view at admin/content/media

- Why do we need both views? 
- How do I upload files outside of the linkit interface?

**Comment by briand44** [comment]
I was thinking about those as well and I think I understand why we are doing it but I am not sure that I agree with it 100%.

I think because a user would have to go to the media view to upload files outside of the linkit ui that we should still treat those files as media even though we aren't adding them through the WYSIWYG the same way as other media entities. I also don't think we need both views but am not really sure what the plan is for that as part of core.

**Comment by genjohnson** [comment]
@adamdelaney My original intention with keeping both the Files and Media tabs was to avoid confusion between the linking & embedding processes (since currently we cannot embed links to files). I chatted with Brian about this a bit and ended up looking into what we can expect from Core in the future... it sounds like [eventually "Files" will go away in favor of "Media"](https://www.drupal.org/project/drupal/issues/2906496#comment-12247111).  Removing the Files tab and listing files on the Media tab is fine with me :)

You should be able to upload files outside of the LinkIt interface by going to `Content > Media > Add media > File` (/media/add/file). I'm getting an error on this page locally right now but it _should_ work, so we might need to investigate that if others have the same issue.

**Comment by genjohnson** [comment]
Remaining tasks:

- [ ]  Do not strip attributes when editing content
- [ ] Remove "Files" tab in favor of "Media" tab
- [ ] Verify files can be uploaded at `/media/add/file`

**Comment by genjohnson** [comment]
@briand44 @adamdelaney I think the [remaining tasks](https://github.com/uiowa/uiowa_profile/pull/97#issuecomment-412687947) have been addressed. Could you give this PR another test?

**Comment by briand44** [comment]
```Warning: file_put_contents(sites/eight.uiowa.edu/files/php/twig/5b733b1b64b70_file-upload-help.html.twi_WMZNPiQT8tKxmVUNwUq0L1oIP/.htaccess): failed to open stream: Permission denied in Drupal\Component\PhpStorage\FileStorage->ensureDirectory() (line 123 of core/lib/Drupal/Component/PhpStorage/FileStorage.php).
Drupal\Component\PhpStorage\FileStorage->ensureDirectory('sites/eight.uiowa.edu/files/php/twig/5b733b1b64b70_file-upload-help.html.twi_WMZNPiQT8tKxmVUNwUq0L1oIP') (Line: 86)
Drupal\Component\PhpStorage\MTimeProtectedFastFileStorage->save('5b733b1b64b70_file-upload-help.html.twi_WMZNPiQT8tKxmVUNwUq0L1oIP', '&lt;?php

/* core/themes/classy/templates/content-edit/file-upload-help.html.twig */
class __TwigTemplate_77090d5c01744d46b9a9853f9880e646deb183a35c544c0b948060e561444744 extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this-&gt;parent = false;

        $this-&gt;blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        $tags = array();
        $filters = array("safe_join" =&gt; 12);
        $functions = array();

        try {
            $this-&gt;env-&gt;getExtension('Twig_Extension_Sandbox')-&gt;checkSecurity(
                array(),
                array('safe_join'),
                array()
            );
        } catch (Twig_Sandbox_SecurityError $e) {
            $e-&gt;setSourceContext($this-&gt;getSourceContext());

            if ($e instanceof Twig_Sandbox_SecurityNotAllowedTagError &amp;&amp; isset($tags[$e-&gt;getTagName()])) {
                $e-&gt;setTemplateLine($tags[$e-&gt;getTagName()]);
            } elseif ($e instanceof Twig_Sandbox_SecurityNotAllowedFilterError &amp;&amp; isset($filters[$e-&gt;getFilterName()])) {
                $e-&gt;setTemplateLine($filters[$e-&gt;getFilterName()]);
            } elseif ($e instanceof Twig_Sandbox_SecurityNotAllowedFunctionError &amp;&amp; isset($functions[$e-&gt;getFunctionName()])) {
                $e-&gt;setTemplateLine($functions[$e-&gt;getFunctionName()]);
            }

            throw $e;
        }

        // line 12
        echo $this-&gt;env-&gt;getExtension('Twig_Extension_Sandbox')-&gt;ensureToStringAllowed($this-&gt;env-&gt;getExtension('Drupal\Core\Template\TwigExtension')-&gt;renderVar($this-&gt;env-&gt;getExtension('Drupal\Core\Template\TwigExtension')-&gt;safeJoin($this-&gt;env, ($context["descriptions"] ?? null), "")));
        echo "
";
    }

    public function getTemplateName()
    {
        return "core/themes/classy/templates/content-edit/file-upload-help.html.twig";
    }

    public function isTraitable()
    {
        return false;
    }

    public function getDebugInfo()
    {
        return array (  43 =&gt; 12,);
    }

    /** @deprecated since 1.27 (to be removed in 2.0). Use getSourceContext() instead */
    public function getSource()
    {
        @trigger_error('The '.__METHOD__.' method is deprecated since version 1.27 and will be removed in 2.0. Use getSourceContext() instead.', E_USER_DEPRECATED);

        return $this-&gt;getSourceContext()-&gt;getCode();
    }

    public function getSourceContext()
    {
        return new Twig_Source("", "core/themes/classy/templates/content-edit/file-upload-help.html.twig", "/app/docroot/core/themes/classy/templates/content-edit/file-upload-help.html.twig");
    }
}
') (Line: 111)
Drupal\Core\Template\TwigPhpStorageCache->write('5b733b1b64b70_file-upload-help.html.twi_WMZNPiQT8tKxmVUNwUq0L1oIP', '&lt;?php

/* core/themes/classy/templates/content-edit/file-upload-help.html.twig */
class __TwigTemplate_77090d5c01744d46b9a9853f9880e646deb183a35c544c0b948060e561444744 extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this-&gt;parent = false;

        $this-&gt;blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        $tags = array();
        $filters = array("safe_join" =&gt; 12);
        $functions = array();

        try {
            $this-&gt;env-&gt;getExtension('Twig_Extension_Sandbox')-&gt;checkSecurity(
                array(),
                array('safe_join'),
                array()
            );
        } catch (Twig_Sandbox_SecurityError $e) {
            $e-&gt;setSourceContext($this-&gt;getSourceContext());

            if ($e instanceof Twig_Sandbox_SecurityNotAllowedTagError &amp;&amp; isset($tags[$e-&gt;getTagName()])) {
                $e-&gt;setTemplateLine($tags[$e-&gt;getTagName()]);
            } elseif ($e instanceof Twig_Sandbox_SecurityNotAllowedFilterError &amp;&amp; isset($filters[$e-&gt;getFilterName()])) {
                $e-&gt;setTemplateLine($filters[$e-&gt;getFilterName()]);
            } elseif ($e instanceof Twig_Sandbox_SecurityNotAllowedFunctionError &amp;&amp; isset($functions[$e-&gt;getFunctionName()])) {
                $e-&gt;setTemplateLine($functions[$e-&gt;getFunctionName()]);
            }

            throw $e;
        }

        // line 12
        echo $this-&gt;env-&gt;getExtension('Twig_Extension_Sandbox')-&gt;ensureToStringAllowed($this-&gt;env-&gt;getExtension('Drupal\Core\Template\TwigExtension')-&gt;renderVar($this-&gt;env-&gt;getExtension('Drupal\Core\Template\TwigExtension')-&gt;safeJoin($this-&gt;env, ($context["descriptions"] ?? null), "")));
        echo "
";
    }

    public function getTemplateName()
    {
        return "core/themes/classy/templates/content-edit/file-upload-help.html.twig";
    }

    public function isTraitable()
    {
        return false;
    }

    public function getDebugInfo()
    {
        return array (  43 =&gt; 12,);
    }

    /** @deprecated since 1.27 (to be removed in 2.0). Use getSourceContext() instead */
    public function getSource()
    {
        @trigger_error('The '.__METHOD__.' method is deprecated since version 1.27 and will be removed in 2.0. Use getSourceContext() instead.', E_USER_DEPRECATED);

        return $this-&gt;getSourceContext()-&gt;getCode();
    }

    public function getSourceContext()
    {
        return new Twig_Source("", "core/themes/classy/templates/content-edit/file-upload-help.html.twig", "/app/docroot/core/themes/classy/templates/content-edit/file-upload-help.html.twig");
    }
}
') (Line: 457)
Twig_Environment->loadTemplate('core/themes/classy/templates/content-edit/file-upload-help.html.twig') (Line: 64)
twig_render_template('core/themes/classy/templates/content-edit/file-upload-help.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('file_upload_help', Array) (Line: 437)
Drupal\Core\Render\Renderer->doRender(Array, 1) (Line: 195)
Drupal\Core\Render\Renderer->render(Array, 1) (Line: 151)
Drupal\Core\Render\Renderer->Drupal\Core\Render\{closure}() (Line: 582)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 152)
Drupal\Core\Render\Renderer->renderPlain(Array) (Line: 264)
Drupal\file\Plugin\Field\FieldWidget\FileWidget->formElement(Object, 0, Array, Array, Object) (Line: 335)
Drupal\Core\Field\WidgetBase->formSingleElement(Object, 0, Array, Array, Object) (Line: 162)
Drupal\file\Plugin\Field\FieldWidget\FileWidget->formMultipleElements(Object, Array, Object) (Line: 104)
Drupal\Core\Field\WidgetBase->form(Object, Array, Object) (Line: 171)
Drupal\Core\Entity\Entity\EntityFormDisplay->buildForm(Object, Array, Object) (Line: 170)
Drupal\inline_entity_form\Form\EntityInlineForm->entityForm(Array, Object) (Line: 124)
Drupal\inline_entity_form\Element\InlineEntityForm::processEntityForm(Array, Object, Array)
call_user_func_array(Array, Array) (Line: 997)
Drupal\Core\Form\FormBuilder->doBuildForm('entity_browser_file_link_browser_form', Array, Object) (Line: 1060)
Drupal\Core\Form\FormBuilder->doBuildForm('entity_browser_file_link_browser_form', Array, Object) (Line: 1060)
Drupal\Core\Form\FormBuilder->doBuildForm('entity_browser_file_link_browser_form', Array, Object) (Line: 561)
Drupal\Core\Form\FormBuilder->processForm('entity_browser_file_link_browser_form', Array, Object) (Line: 318)
Drupal\Core\Form\FormBuilder->buildForm('entity_browser_file_link_browser_form', Object) (Line: 93)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 582)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 151)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 665)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)```

I get this error when I first go to add content and click the linkit button and expand the upload a file fieldset. Running 8.6.0-beta2

**Comment by briand44** [comment]
The error above goes away after the first time using the linkit button and doesn't come back.

**Comment by briand44** [comment]
I can confirm files are linking directly to the file itself and not the file entity. This continues to work after re-saving.

**Comment by briand44** [comment]
Another issue I noticed and not sure if it is related to this issue but the media library tab in our media wysiwyg entity browser is defaulting to filtering by audio rather than any.

**Comment by briand44** [comment]
I can confirm that the admin/content/files tab is gone from content page and can't be viewed directly at the url.

**Comment by briand44** [comment]
I am not sure how I feel about removing the Upload file(s) tab on our media wysiwyg browser. Since the current media library (view) shows uploaded files they can still be embedded using the media wysiwyg browser so does it make since to restrict them from uploading here?

**Comment by genjohnson** [comment]
The media library (view) showing uploaded files in the media wysiwyg browser is unintentional...I think that's a regression which was introduced in the last few commits I made.

So tasks remaining:
- [ ] Set "Type" filter default value to "Any"
- [ ] Add a filter to not include files in the Media WYSIWYG Browser

**Comment by genjohnson** [comment]
Since the PR to update to 8.6.x has been merged in (making Media Library available), I'm closing this PR in favor of work in progress on the `media_library` branch. The work there will fix the outstanding tasks identified in the comments here.

**Pull request closed without merging**
