### PR TITLE
Seo

### PR DESCRIPTION
**Pull request by adamdelaney**
## Feature sets
- Provides configuration to include basic pages as part of the sitemap.
- Enables Google Analytics module.
- Enables Metatag module.
- Enables schema_metatage, schema_web_site and schema_article modules/sub-modules.

## Todo
- [x] Implement default configuration for global metatags.
- [ ] Implement default configuration for schema.org web site #87
- [x] Set change frequency for basic pages (sitemap config).
- [x] Allow webmasters to configure google analytics #76 
- [x] Allow webmasters to submit sitemaps #75
- [x] Enable and permit webmasters to verify their site. #75 
- [ ] Include page number in page title global config. #91 
- [ ] Documentation for editors #90

### CODE REVIEW

**Comment by briand44** [comment]
I think we should scope this PR to just include enabling modules and configuring global defaults. I feel like any content type specific settings (schema.org for basic pages) should fall under a PR for that feature.

**Comment by briand44** [comment]
We also need to decide what ability we plan on giving to content editors. Should they have the ability to override global config? Should they override individual entities?

**Comment by adamdelaney** [comment]
@briand44 I checked what is allowed for webmasters on the d7 standard service.
- Webmasters can modify global verification
- Webmasters can modify global xmlsitemap config, but they do not have the ability to include/exclude based on content type.
- Webmasters can override metatags on a per node basis.

**Comment by briand44** [comment]
In D7 we currently have the advanced permissions on for metatags where we can grant permissions for each specific meta tag. D8 issue for this functionality https://www.drupal.org/project/metatag/issues/2782797

**Comment by briand44** [comment]
In order to allow editors to override default meta tags on individual entities we need to add the meta tag field to each entity type. This is out of scope for this PR and should be included in future PR's for each entity type (basic pages, articles, etc.).

**Comment by genjohnson** [comment]
I've open #80 as a follow-up task so that editors can override meta tag defaults on Basic Page entities.

**Comment by joewhitsitt** [comment]
screen shot 2018-05-14 at 2 10 35 pm

@briand44 I am seeing two generator meta tags with the latest commit.

**Comment by briand44** [comment]
https://www.drupal.org/project/metatag/issues/2735195

**Pull request merged**
