### PR TITLE
Initial media/WYSIWYG implementation.

### PR DESCRIPTION
**Pull request by richardbporter**
Starting a PR to track discussion, issues, etc. Also makes integration easier. This address https://github.com/uiowa/uiowa_profile/projects/1#card-7754465 for D8 MVP.

## Feature sets in this PR
- Upload images and files as media using media_entity_browser.
- Adds the ability to embed image and file media assets via entity_embed into the wysiwyg.
- Has ability to caption images through WYSIWYG.
- Adds logic to restrict display plugins based upon a media bundle as well as cleans up form items for file media types.
- Adds logical view modes for displaying image media entities (media:image_small, media:image_medium, media:image_large).
- Requires adding alt text to image media entities when upload.
- Creates a media library to reuse existing media.
- Creates a filtered html text format.
- Adds ability to scale and crop images based on focal point.
- Implements better internal linking via wysiwyg link button, including autocomplete and additional attributes.
- Creates new form displays to clean up core's media entity form when uploading via media_entity_browser.

## How to test
1. Edit `composer.json` file located at the application root.
2. Update uiowa/uiowa_profile to `dev-uiowa_media_wysiwyg`.
3. Save and close the file.
4. From the command line run: `composer update uiowa/uiowa_profile`.
5. Run a site-install: `drush si`.
6. Check features sets (see above) and other general media and wysiwyg functionality.

### CODE REVIEW

**Comment by briand44** [comment]
Here are a few items that could be added or improved.

TO DO:
Entity Browser Styles
Captioning for images added using a field?
Cropping
Additional view modes for rendering media
Ability to add alt text during upload
Package an icon for media entity embed button
Handling of Audio & Video embeds
Dropzonejs?

**Comment by briand44** [comment]
Thumbnails not generated. See #38

**Comment by adamdelaney** [comment]
## Embed options

### URL Embed
I've have tested out the url_embed module. This works well for quickly embedding rich media into the WYSIWYG. It creates an embed button that can be implemented via your text_format. This module does not create file/media entities and does not look like it will work within an entity browser, see: https://www.drupal.org/project/url_embed/issues/2956125. 

### Media embeds
The other option is to add additional projects to support remote assets such as video and audio. See: https://www.drupal.org/project/media_entity for a list of media providers. Here looks like some useful ones:

- https://www.drupal.org/project/video_embed_field
- https://www.drupal.org/project/media_entity_twitter
- https://www.drupal.org/project/media_entity_instagram
- https://www.drupal.org/project/media_entity_soundcloud
- https://www.drupal.org/project/media_entity_facebook
- https://www.drupal.org/project/media_entity_flickr

**Comment by adamdelaney** [comment]
I've tested the updated media_wysiwyg form displays and they look good. I noticed a couple of issues.

## Image styles show broken image
All of the image styles other than original show broken images.
screen shot 2018-03-26 at 1 43 26 pm

## Media Entity Browser thumbnail style
This image style doesn't make any sense.
screen shot 2018-03-26 at 1 44 04 pm

## No thumbnail on image upload
There is no thumbnail preview when uploading.
screen shot 2018-03-26 at 1 47 54 pm

**Comment by adamdelaney** [comment]
From what I can tell the thumbnail entity embed display plugin provided in the Embed Buttons configuration is part of the media module (or one of it's dependencies). The display plugin does not exist until we enable core's media module.

**Comment by briand44** [comment]
I guess if that is the case it should be safe to use and I think we should look into a way to exclude image styles rather than creating a bunch of new view modes.

**Comment by adamdelaney** [comment]
I just read an issue that suggests that the thumbnail field formatter should not be used for content display. See: https://www.drupal.org/project/media_entity/issues/2844028 and https://www.drupal.org/node/2850169.

**Comment by briand44** [comment]
I did some testing and found a few small issues.

1. We should update embed button icon for media entity embed button to eliminate any confusion with the core image handling embed button.
2. Should we add caption styles to our uiowa_media_wysiwyg module or should those live in the base theme?
3. Label shows for media images and files added through ckeditor.
4. Can't add inline files.
5. We should probably adjust our custom view modes to use focal point.
6. There is a bug when using the media library and selecting more entities than a field is configured for.
7. Linkit is not enabled on the text format by default and the url converter checkbox not checked.
8. Advanced link module not working by default because "title", "class", "id", "target" and/or the "rel" attributes are not whitelisted in the text format.

**Comment by adamdelaney** [comment]
> Should we add caption styles to our uiowa_media_wysiwyg module or should those live in the base theme?
I believe these styles should be in the theme or left to a developer to implement. We should be as un-opinionated as possible.

> Label shows for media images and files added through ckeditor when editing an entity.
We should create an issue for this and decide if it is an MVP blocker.

> There is a bug when using the media library and selecting more entities than a field is configured for.
We should create an issue for this and decide if it is an MVP blocker.

**Comment by ashybaye** [comment]
More feedback from testing:
- add anchor links functionality
- add more config options for tables (width, summary)
- add a11y requirements for table headers (ex: scope="col")
- add text alignment buttons
- add styles for Large text and primary button
- add the ability to add layouts (did we decide to use Bootstrap layouts?) - should this come after we install the Bootstrap theme?

- <media-related> the code produced by media embed when placing an image is just weird. Is there a way to clean it up?

**Comment by briand44** [comment]
@ashybaye https://github.com/uiowa/uiowa_profile/issues/42 relates to your first item.

**Comment by richardbporter** [comment]
I think it makes sense to not link images embedded in the WYSIWYG to the file entity by default. I can change that unless disagrees.

**Comment by bspeare** [comment]
This works pretty great.  I am wondering what your thoughts are on the "Selected entity" link in the Embed media pop-up.  Will you hide or disable that link at some point?

I also encountered a lot of CKEditor Javascript errors testing this on Chrome 65 and Opera 49 that were similar to https://www.drupal.org/project/entity_embed/issues/2544020 if there is any concern about editors using slightly older browsers.

**Comment by adamdelaney** [comment]
@bspeare Thanks for the feedback.
> I am wondering what your thoughts are on the "Selected entity" link in the Embed media pop-up. Will you hide or disable that link at some point?
I have created an issue for this see #77
> How will users add links to images? Will that functionality be added in at a later point?
I have created an issue for this see #78
> I encountered a lot of CKEditor JavaScript errors...
I did not see any JS errors could you provide more details.

**Comment by bspeare** [comment]
Here's a couple examples of the browser issues that I noticed:

BrowserStack, Mac OS Sierra Chrome 65
- If I embed a file into the content area I can't type or advance the cursor from the file focus.  Tabbing or arrow keys will not help either.   If I paste some text into the editor it pastes over the embedded file link.

BrowserStack, Mac OS El Capitan Chrome 65
- Same issue with text focus.  Sometimes if I try to reopen the file entity link the "Embed" button will not close the window and I will get the console errors in the attached screenshot. 

Probably not a blocker, but it seems pretty buggy on some browsers. 

screen shot 2018-04-30 at 10 01 07 am

**Comment by adamdelaney** [comment]
@bspeare Thanks for more details. Can you go ahead and open a new issue with this info. This looks like something we want to keep an eye on. I'd also include the link to the Drupal.org issue as well. Thanks!

**Pull request merged**
