### PR TITLE
Main navigation

### PR DESCRIPTION
**Pull request by genjohnson**
This PR addresses #43 by:

- creating and placing a Superfish menu block for top-level links
- creating and placing a menu_block block for level 2+ menu links
- assigning permissions for editors & webmasters to manage the Main Navigation menu

**Note:** As a follow-up issue, the block placements provided here will need to be changed once we have a custom theme set as the default.

**To test this PR:**
1. Check out the `superfish` branch of uiowa801.
2. Run `composer install`.
3. Run `drush si uiowa` for some site.
4. Add some content to the Main menu.
5. Verify that:
    - editors & webmasters can add Basic Pages to the Main menu from the node add/edit form
    - editors & webmasters can manage only the Main menu at admin/structure/menu
    - the superfish block and menu_block block display

### CODE REVIEW

**Comment by GaryRidgway** [comment]
reviewed the superfish functionality and verified that:
- webmasters and editors could add/remove/edit links in the menu, including external and internal pages
- webmasters and editors can only manage the main menu and no other menus
- the superfish block appears on the blocks page

However, the menu_block block does not appear on the blocks page currently, and it would be expected for it to show up under the content section.

**Comment by briand44** [comment]
My testing verifies what Alan said. Superfish menu shows up and works as expected but not seeing the menu block.

**Comment by genjohnson** [comment]
@GaryRidgway @briand44 I've updated `composer.lock` in the superfish branch of the uiowa801 application - it looks like that was behind so you weren't getting the latest commits on the superfish branch of uiowa_profile.

Could you try this again?

**Comment by genjohnson** [comment]
A couple of issues referencing the behavior of the block title always displaying:
- [Add option to show block if menu tree contains no links](https://www.drupal.org/project/menu_block/issues/2757215)
- [PHP notice "Undefined index: menu_name" when menu tree is empty](https://www.drupal.org/project/menu_block/issues/2765411)

**Comment by genjohnson** [comment]
After more investigation, it turns out this behavior of a menu block rendering when it is empty (and nothing should be returned) is a bug in Drupal core: https://www.drupal.org/project/drupal/issues/2642816

**Comment by genjohnson** [comment]
Down the rabbit hole of d.o issues even further is [[meta] Themes improperly check renderable arrays when determining visibility](https://www.drupal.org/project/drupal/issues/953034). This is a big, deep issue of how the render API works in D8 and is not expected to be fixed any time soon (this has already been a known issue for several years).

There are a couple of approaches to getting around this issue by editing page.html.twig, which we might be able to implement in a common base theme to move forward. I'll do a little more investigation into this and report back.

**Comment by genjohnson** [comment]
Here's a patch that addresses the issue of the block title displaying on pages without menu links. I'm still trying to determine if this is an issue with menu_block itself or an issue specific to our setup, so I haven't submitted the patch to d.o yet.

[menu_block-hide_block_if_no_links.patch.txt](https://github.com/uiowa/uiowa_profile/files/1903623/menu_block-hide_block_if_no_links.patch.txt)

**Pull request merged**
